#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"
BASE_IMAGE_ENLARGEROOT=10500
BASE_IMAGE_RESIZEROOT=600
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="raspberry"

# Image source
DOWNLOAD_URL_CHECKSUM="https://github.com/mainsail-crew/armbian-builds/releases/download/20230209-1451/armbian-orangepi3_lts.img.sha256"
DOWNLOAD_URL_IMAGE="https://github.com/mainsail-crew/armbian-builds/releases/download/20230209-1451/armbian-orangepi3_lts.img.xz"

# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

export MODULES="base,pkgupgrade(network,armbian,klipper,node,is_req_preinstall,moonraker,ratos(mainsail,crowsnest,linear_movement_analysis,timelapse,klipperscreen,rpi_mcu,disable-services(hotspot),dfu-util),password-for-sudo),postrename"