#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"
BASE_IMAGE_ENLARGEROOT=10500
BASE_IMAGE_RESIZEROOT=600
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="raspberry"
#only needed for official armbian images
export BASE_DISTRO=armbian
export BASE_ROOT_PARTITION=1

# Image source
DOWNLOAD_URL_CHECKSUM="https://armbian.chi.auroradev.org/dl/orangepi3-lts/archive/Armbian_22.11.1_Orangepi3-lts_bullseye_current_5.15.80.img.xz.sha"
DOWNLOAD_URL_IMAGE="https://armbian.chi.auroradev.org/dl/orangepi3-lts/archive/Armbian_22.11.1_Orangepi3-lts_bullseye_current_5.15.80.img.xz"

# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

export MODULES="base,passwordless_sudo,pkgupgrade(network,armbian,klipper,node,is_req_preinstall,moonraker,ratos(mainsail,crowsnest,linear_movement_analysis,timelapse,klipperscreen,rpi_mcu,disable-services(hotspot_cb1),dfu-util),password-for-sudo),postrename"