#!/usr/bin/env bash
#### opiconfig - SB1 Configuration Module
#from https://www.reddit.com/r/BIGTREETECH/comments/xfom6n/comment/it32e6v/

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Ee

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Enable SPI interface on SBC ..."

# Step 1: Copy default config to backup file
cp "${SPI_CONFIG_TXT_FILE}" "${SPI_CONFIG_BAK_FILE}"

# Step 2: Enable SPI
echo "overlays=spi" >> "${SPI_CONFIG_TXT_FILE}"
echo "spidevparam_spidev_spi_bus=1" >> "${SPI_CONFIG_TXT_FILE}"
echo "param_spidev_spi_cs=1" >> "${SPI_CONFIG_TXT_FILE}"
echo "param_spidev_max_freq=1000000" >> "${SPI_CONFIG_TXT_FILE}"

echo_green "Enable SPI interface on SBC ... DONE!"